name: Continuous Integration

on:
  pull_request: ~
  workflow_dispatch: ~
  schedule:
    - cron: "0 1 * * 1,4" # Run at 1am every Monday & Thursday

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    name: 🚧 Build 🚧

    strategy:
      matrix:
        node: [16.x]

    steps:
    
      # --- ⚙️ Setup ⚙️ ----------

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Cache node
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node

      # --- 🛠 Test 🛠 ----------

      - name: Validate renovate
        uses: rinchsan/renovate-config-validator@v0.0.10
        with:
          pattern: '*.json'
