name: Continuous Integration

on:
    pull_request: ~
    workflow_dispatch: ~
    schedule:
        - cron: 0 1 * * 1,4 # Run at 1am every Monday & Thursday

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 5

        name: 🚧 Build 🚧 | Node ${{ matrix.node }}

        strategy:
            matrix:
                node: [16.x]

        steps:
            # --- ⚙️ Setup ⚙️ ----------

            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup node
                uses: actions/setup-node@v6
                with:
                    node-version: ${{ matrix.node }}

            -   name: Cache node
                uses: actions/cache@v4
                with:
                    path: ~/.npm
                    key: ${{ runner.os }}-node-${{ matrix.node }}
                    restore-keys: |
                        ${{ runner.os }}-node-

            # --- 🛠 Test 🛠 ----------

            -   name: Validate renovate
                uses: rinchsan/renovate-config-validator@v0.0.12
                with:
                    pattern: "*.json"
